version: "3.5"

services:
  app:
    image: 'web-rise'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/WebRise
      DB_USERNAME: user
      DB_PASSWORD: user
      DB_NAME: WebRise

  db:
    container_name: db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=WebRise