spring:
  application:
    name: WebRise
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/WebRise}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/master.xml
